# Generated by Django 5.2.11 on 2026-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrftoken', models.CharField(default=1)),
                ('inp', models.CharField()),
                ('sol', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInpSol',
        ),
    ]
